# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: timestamp/timestamp.proto, trade.proto, trade_aggregation.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Timestamp(betterproto.Message):
    """
    Timestamp is a point in time represented as seconds and fractions of
    seconds at nanosecond resolution in UTC since Unix epoch.
    """

    seconds: int = betterproto.fixed32_field(1)
    nanoseconds: int = betterproto.fixed32_field(2)


@dataclass(eq=False, repr=False)
class TradeAggregation(betterproto.Message):
    """Represents aggregated trade data for a specific time period"""

    open: float = betterproto.double_field(1)
    """Opening price for the aggregation period"""

    high: float = betterproto.double_field(2)
    """Highest price reached during the aggregation period"""

    low: float = betterproto.double_field(3)
    """Lowest price reached during the aggregation period"""

    close: float = betterproto.double_field(4)
    """Closing price for the aggregation period"""

    volume: float = betterproto.double_field(5)
    """Total trading volume during the aggregation period"""

    timestamp: "Timestamp" = betterproto.message_field(6)
    """Timestamp representing the start of the aggregation period"""

    first_timestamp: "Timestamp" = betterproto.message_field(7)
    """Timestamp of the first trade in the aggregation period"""

    last_timestamp: "Timestamp" = betterproto.message_field(8)
    """Timestamp of the last trade in the aggregation period"""


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    """Represents a single trade transaction"""

    id: str = betterproto.string_field(1)
    """Unique exchange-native identifier of the trade"""

    price: float = betterproto.double_field(2)
    """Price at which the trade was executed"""

    amount: float = betterproto.double_field(3)
    """Quantity of the asset traded"""

    timestamp: "Timestamp" = betterproto.message_field(4)
    """Timestamp when the trade occurred"""
